In [1]:
import pandas as pd

#working with JSON

In [2]:
# df = pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

In [3]:
# print(df)

##Working with SQL

In [4]:
import mysql.connector

In [5]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [9]:
pd.read_sql_query("SELECT * FROM city WHERE CountryCode	LIKE 'PAK'",conn)

C:\Users\Rocky computer\AppData\Local\Temp\ipykernel_10896\2308314886.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city WHERE CountryCode	LIKE 'PAK'",conn)

      ID              Name CountryCode              District  Population
0   2822           Karachi         PAK                 Sindh     9269265
1   2823            Lahore         PAK                Punjab     5063499
2   2824        Faisalabad         PAK                Punjab     1977246
3   2825        Rawalpindi         PAK                Punjab     1406214
4   2826            Multan         PAK                Punjab     1182441
5   2827         Hyderabad         PAK                 Sindh     1151274
6   2828        Gujranwala         PAK                Punjab     1124749
7   2829          Peshawar         PAK  Nothwest Border Prov      988005
8   2830            Quetta         PAK           Baluchistan      560307
9   2831         Islamabad         PAK             Islamabad      524500
10  2832          Sargodha         PAK                Punjab      455360
11  2833           Sialkot         PAK                Punjab      417597
12  2834        Bahawalpur         PAK                Punjab      403408
13  2835            Sukkur         PAK                 Sindh      329176
14  2836             Jhang         PAK                Punjab      292214
15  2837       Sheikhupura         PAK                Punjab      271875
16  2838           Larkana         PAK                 Sindh      270366
17  2839            Gujrat         PAK                Punjab      250121
18  2840            Mardan         PAK  Nothwest Border Prov      244511
19  2841             Kasur         PAK                Punjab      241649
20  2842    Rahim Yar Khan         PAK                Punjab      228479
21  2843           Sahiwal         PAK                Punjab      207388
22  2844             Okara         PAK                Punjab      200901
23  2845               Wah         PAK                Punjab      198400
24  2846   Dera Ghazi Khan         PAK                Punjab      188100
25  2847       Mirpur Khas         PAK                  Sind      184500
26  2848         Nawabshah         PAK                  Sind      183100
27  2849           Mingora         PAK  Nothwest Border Prov      174500
28  2850           Chiniot         PAK                Punjab      169300
29  2851            Kamoke         PAK                Punjab      151000
30  2852    Mandi Burewala         PAK                Punjab      149900
31  2853            Jhelum         PAK                Punjab      145800
32  2854         Sadiqabad         PAK                Punjab      141500
33  2855         Jacobabad         PAK                  Sind      137700
34  2856         Shikarpur         PAK                  Sind      133300
35  2857          Khanewal         PAK                Punjab      133000
36  2858         Hafizabad         PAK                Punjab      130200
37  2859             Kohat         PAK  Nothwest Border Prov      125300
38  2860      Muzaffargarh         PAK                Punjab      121600
39  2861           Khanpur         PAK                Punjab      117800
40  2862             Gojra         PAK                Punjab      115000
41  2863      Bahawalnagar         PAK                Punjab      109600
42  2864           Muridke         PAK                Punjab      108600
43  2865        Pak Pattan         PAK                Punjab      107800
44  2866         Abottabad         PAK  Nothwest Border Prov      106000
45  2867        Tando Adam         PAK                  Sind      103400
46  2868         Jaranwala         PAK                Punjab      103300
47  2869          Khairpur         PAK                  Sind      102200
48  2870   Chishtian Mandi         PAK                Punjab      101700
49  2871             Daska         PAK                Punjab      101500
50  2872              Dadu         PAK                  Sind       98600
51  2873   Mandi Bahauddin         PAK                Punjab       97300
52  2874     Ahmadpur East         PAK                Punjab       96000
53  2875           Kamalia         PAK                Punjab       95300
54  2876           Khuzdar         PAK           Baluchistan       93100
55  2877            Vihari         PAK                Punjab       92300
56  2878  Dera Ismail Khan         PAK  Nothwest Border Prov       90400
57  2879         Wazirabad         PAK                Punjab       89700
58  2880          Nowshera         PAK  Nothwest Border Prov       89400

In [11]:
pd.read_sql_query("SELECT * FROM country WHERE Continent LIKE 'Oceania'",conn)

C:\Users\Rocky computer\AppData\Local\Temp\ipykernel_10896\3600098414.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM country WHERE Continent LIKE 'Oceania'",conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ASM,American Samoa,Oceania,Polynesia,199.0,NaN,68000,75.1,334.0,NaN,Amerika Samoa,US Territory,George W. Bush,54.0,AS
1,AUS,Australia,Oceania,Australia and New Zealand,7741220.0,1901.0,18886000,79.8,351182.0,392911.0,Australia,"Constitutional Monarchy, Federation",Elisabeth II,135.0,AU
2,CCK,Cocos (Keeling) Islands,Oceania,Australia and New Zealand,14.0,NaN,600,NaN,0.0,NaN,Cocos (Keeling) Islands,Territory of Australia,Elisabeth II,2317.0,CC
3,COK,Cook Islands,Oceania,Polynesia,236.0,NaN,20000,71.1,100.0,NaN,The Cook Islands,Nonmetropolitan Territory of New Zealand,Elisabeth II,583.0,CK
4,CXR,Christmas Island,Oceania,Australia and New Zealand,135.0,NaN,2500,NaN,0.0,NaN,Christmas Island,Territory of Australia,Elisabeth II,1791.0,CX
5,FJI,Fiji Islands,Oceania,Melanesia,18274.0,1970.0,817000,67.9,1536.0,2149.0,Fiji Islands,Republic,Josefa Iloilo,764.0,FJ
6,FSM,"Micronesia, Federated States of",Oceania,Micronesia,702.0,1990.0,119000,68.6,212.0,NaN,Micronesia,Federal Republic,Leo A. Falcam,2689.0,FM
7,GUM,Guam,Oceania,Micronesia,549.0,NaN,168000,77.8,1197.0,1136.0,Guam,US Territory,George W. Bush,921.0,GU
8,KIR,Kiribati,Oceania,Micronesia,726.0,1979.0,83000,59.8,40.7,NaN,Kiribati,Republic,Teburoro Tito,2256.0,KI
9,MHL,Marshall Islands,Oceania,Micronesia,181.0,1990.0,64000,65.5,97.0,NaN,Marshall Islands/Majol,Republic,Kessai Note,2507.0,MH
10,MNP,Northern Mariana Islands,Oceania,Micronesia,464.0,NaN,78000,75.5,0.0,NaN,Northern Mariana Islands,Commonwealth of the US,George W. Bush,2913.0,MP
11,NCL,New Caledonia,Oceania,Melanesia,18575.0,NaN,214000,72.8,3563.0,NaN,Nouvelle-Calédonie,Nonmetropolitan Territory of France,Jacques Chirac,3493.0,NC
12,NFK,Norfolk Island,Oceania,Australia and New Zealand,36.0,NaN,2000,NaN,0.0,NaN,Norfolk Island,Territory of Australia,Elisabeth II,2806.0,NF
13,NIU,Niue,Oceania,Polynesia,260.0,NaN,2000,NaN,0.0,NaN,Niue,Nonmetropolitan Territory of New Zealand,Elisabeth II,2805.0,NU
14,NRU,Nauru,Oceania,Micronesia,21.0,1968.0,12000,60.8,197.0,NaN,Naoero/Nauru,Republic,Bernard Dowiyogo,2728.0,NR
15,NZL,New Zealand,Oceania,Australia and New Zealand,270534.0,1907.0,3862000,77.8,54669.0,64960.0,New Zealand/Aotearoa,Constitutional Monarchy,Elisabeth II,3499.0,NZ
16,PCN,Pitcairn,Oceania,Polynesia,49.0,NaN,50,NaN,0.0,NaN,Pitcairn,Dependent Territory of the UK,Elisabeth II,2912.0,PN
17,PLW,Palau,Oceania,Micronesia,459.0,1994.0,19000,68.6,105.0,NaN,Belau/Palau,Republic,Kuniwo Nakamura,2881.0,PW
18,PNG,Papua New Guinea,Oceania,Melanesia,462840.0,1975.0,4807000,63.1,4988.0,6328.0,Papua New Guinea/Papua Niugini,Constitutional Monarchy,Elisabeth II,2884.0,PG
19,PYF,French Polynesia,Oceania,Polynesia,4000.0,NaN,235000,74.8,818.0,781.0,Polynésie française,Nonmetropolitan Territory of France,Jacques Chirac,3016.0,PF
20,SLB,Solomon Islands,Oceania,Melanesia,28896.0,1978.0,444000,71.3,182.0,220.0,Solomon Islands,Constitutional Monarchy,Elisabeth II,3161.0,SB
21,TKL,Tokelau,Oceania,Polynesia,12.0,NaN,2000,NaN,0.0,NaN,Tokelau,Nonmetropolitan Territory of New Zealand,Elisabeth II,3333.0,TK
22,TON,Tonga,Oceania,Polynesia,650.0,1970.0,99000,67.9,146.0,170.0,Tonga,Monarchy,Taufa'ahau Tupou IV,3334.0,TO
23,TUV,Tuvalu,Oceania,Polynesia,26.0,1978.0,12000,66.3,6.0,NaN,Tuvalu,Constitutional Monarchy,Elisabeth II,3424.0,TV
24,UMI,United States Minor Outlying Islands,Oceania,Micronesia/Caribbean,16.0,NaN,0,NaN,0.0,NaN,United States Minor Outlying Islands,Dependent Territory of the US,George W. Bush,NaN,UM
25,VUT,Vanuatu,Oceania,Melanesia,12189.0,1980.0,190000,60.6,261.0,246.0,Vanuatu,Republic,John Bani,3537.0,VU
26,WLF,Wallis and Futuna,Oceania,Polynesia,200.0,NaN,15000,NaN,0.0,NaN,Wallis-et-Futuna,Nonmetropolitan Territory of France,Jacques Chirac,3536.0,WF
27,WSM,Samoa,Oceania,Polynesia,2831.0,1962.0,180000,69.2,141.0,157.0,Samoa,Parlementary Monarchy,Malietoa Tanumafili II,3169.0,WS

In [13]:
pd.read_sql_query("SELECT * FROM country WHERE SurfaceArea > 700000",conn)

C:\Users\Rocky computer\AppData\Local\Temp\ipykernel_10896\1946084735.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM country WHERE SurfaceArea > 700000",conn)

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
1,ARG,Argentina,South America,South America,2780400.0,1816.0,37032000,75.1,340238.0,323310.0,Argentina,Federal Republic,Fernando de la Rúa,69.0,AR
2,ATA,Antarctica,Antarctica,Antarctica,13120000.0,NaN,0,NaN,0.0,NaN,–,Co-administrated,,NaN,AQ
3,AUS,Australia,Oceania,Australia and New Zealand,7741220.0,1901.0,18886000,79.8,351182.0,392911.0,Australia,"Constitutional Monarchy, Federation",Elisabeth II,135.0,AU
4,BOL,Bolivia,South America,South America,1098581.0,1825.0,8329000,63.7,8571.0,7967.0,Bolivia,Republic,Hugo Bánzer Suárez,194.0,BO
5,BRA,Brazil,South America,South America,8547403.0,1822.0,170115000,62.9,776739.0,804108.0,Brasil,Federal Republic,Fernando Henrique Cardoso,211.0,BR
6,CAN,Canada,North America,North America,9970610.0,1867.0,31147000,79.4,598862.0,625626.0,Canada,"Constitutional Monarchy, Federation",Elisabeth II,1822.0,CA
7,CHL,Chile,South America,South America,756626.0,1810.0,15211000,75.7,72949.0,75780.0,Chile,Republic,Ricardo Lagos Escobar,554.0,CL
8,CHN,China,Asia,Eastern Asia,9572900.0,-1523.0,1277558000,71.4,982268.0,917719.0,Zhongquo,People'sRepublic,Jiang Zemin,1891.0,CN
9,COD,"Congo, The Democratic Republic of the",Africa,Central Africa,2344858.0,1960.0,51654000,48.8,6964.0,2474.0,République Démocratique du Congo,Republic,Joseph Kabila,2298.0,CD
10,COL,Colombia,South America,South America,1138914.0,1810.0,42321000,70.3,102896.0,105116.0,Colombia,Republic,Andrés Pastrana Arango,2257.0,CO
11,DZA,Algeria,Africa,Northern Africa,2381741.0,1962.0,31471000,69.7,49982.0,46966.0,Al-Jaza’ir/Algérie,Republic,Abdelaziz Bouteflika,35.0,DZ
12,EGY,Egypt,Africa,Northern Africa,1001449.0,1922.0,68470000,63.3,82710.0,75617.0,Misr,Republic,Hosni Mubarak,608.0,EG
13,ETH,Ethiopia,Africa,Eastern Africa,1104300.0,-1000.0,62565000,45.2,6353.0,6180.0,YeItyop´iya,Republic,Negasso Gidada,756.0,ET
14,GRL,Greenland,North America,North America,2166090.0,NaN,56000,68.1,0.0,NaN,Kalaallit Nunaat/Grønland,Part of Denmark,Margrethe II,917.0,GL
15,IDN,Indonesia,Asia,Southeast Asia,1904569.0,1945.0,212107000,68.0,84982.0,215002.0,Indonesia,Republic,Abdurrahman Wahid,939.0,ID
16,IND,India,Asia,Southern and Central Asia,3287263.0,1947.0,1013662000,62.5,447114.0,430572.0,Bharat/India,Federal Republic,Kocheril Raman Narayanan,1109.0,IN
17,IRN,Iran,Asia,Southern and Central Asia,1648195.0,1906.0,67702000,69.7,195746.0,160151.0,Iran,Islamic Republic,Ali Mohammad Khatami-Ardakani,1380.0,IR
18,KAZ,Kazakstan,Asia,Southern and Central Asia,2724900.0,1991.0,16223000,63.2,24375.0,23383.0,Qazaqstan,Republic,Nursultan Nazarbajev,1864.0,KZ
19,LBY,Libyan Arab Jamahiriya,Africa,Northern Africa,1759540.0,1951.0,5605000,75.5,44806.0,40562.0,Libiya,Socialistic State,Muammar al-Qadhafi,2441.0,LY
20,MEX,Mexico,North America,Central America,1958201.0,1810.0,98881000,71.5,414972.0,401461.0,México,Federal Republic,Vicente Fox Quesada,2515.0,MX
21,MLI,Mali,Africa,Western Africa,1240192.0,1960.0,11234000,46.7,2642.0,2453.0,Mali,Republic,Alpha Oumar Konaré,2482.0,ML
22,MNG,Mongolia,Asia,Eastern Asia,1566500.0,1921.0,2662000,67.3,1043.0,933.0,Mongol Uls,Republic,Natsagiin Bagabandi,2696.0,MN
23,MOZ,Mozambique,Africa,Eastern Africa,801590.0,1975.0,19680000,37.5,2891.0,2711.0,Moçambique,Republic,Joaquím A. Chissano,2698.0,MZ
24,MRT,Mauritania,Africa,Western Africa,1025520.0,1960.0,2670000,50.8,998.0,1081.0,Muritaniya/Mauritanie,Republic,Maaouiya Ould Sid´Ahmad Taya,2509.0,MR
25,NAM,Namibia,Africa,Southern Africa,824292.0,1990.0,1726000,42.5,3101.0,3384.0,Namibia,Republic,Sam Nujoma,2726.0,NA
26,NER,Niger,Africa,Western Africa,1267000.0,1960.0,10730000,41.3,1706.0,1580.0,Niger,Republic,Mamadou Tandja,2738.0,NE
27,NGA,Nigeria,Africa,Western Africa,923768.0,1960.0,111506000,51.6,65707.0,58623.0,Nigeria,Federal Republic,Olusegun Obasanjo,2754.0,NG
28,PAK,Pakistan,Asia,Southern and Central Asia,796095.0,1947.0,156483000,61.1,61289.0,58549.0,Pakistan,Republic,Mohammad Rafiq Tarar,2831.0,PK
29,PER,Peru,South America,South America,1285216.0,1821.0,25662000,70.0,64140.0,65186.0,Perú/Piruw,Republic,Valentin Paniagua Corazao,2890.0,PE
30,RUS,Russian Federation,Europe,Eastern Europe,17075400.0,1991.0,146934000,67.2,276608.0,442989.0,Rossija,Federal Republic,Vladimir Putin,3580.0,RU
31,SAU,Saudi Arabia,Asia,Middle East,2149690.0,1932.0,21607000,67.8,137635.0,146171.0,Al-´Arabiya as-Sa´udiya,Monarchy,Fahd ibn Abdul-Aziz al-Sa´ud,3173.0,SA
32,SDN,Sudan,Africa,Northern Africa,2505813.0,1956.0,29490000,56.6,10162.0,NaN,As-Sudan,Islamic Republic,Omar Hassan Ahmad al-Bashir,3225.0,SD
33,TCD,Chad,Africa,Central Africa,1284000.0,1960.0,7651000,50.5,1208.0,1102.0,Tchad/Tshad,Republic,Idriss Déby,3337.0,TD
34,TUR,Turkey,Asia,Middle East,774815.0,1923.0,66591000,71.0,210721.0,189122.0,Türkiye,Republic,Ahmet Necdet Sezer,3358.0,TR
35,TZA,Tanzania,Africa,Eastern Africa,883749.0,1961.0,33517000,52.3,8005.0,7388.0,Tanzania,Republic,Benjamin William Mkapa,3306.0,TZ
36,USA,United States,North America,North America,9363520.0,1776.0,278357000,77.1,8510700.0,8110900.0,United States,Federal Republic,George W. Bush,3813.0,US
37,VEN,Venezuela,South America,South America,912050.0,1811.0,24170000,73.1,95023.0,88434.0,Venezuela,Federal Republic,Hugo Chávez Frías,3539.0,VE
38,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,ZA
39,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,ZM